project:
  type: website

website:
  title: "TUMO project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dataanalysis.qmd
        text: Data Analysis
      - href: sources.qmd
        text: Sources
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
